- name: Configure repo and install Docker on machine
  hosts: all
  become: true
  tasks:
    - name:    Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Install python-pip
      apt:
        name: python-pip
        update_cache: yes
  
    - name: Install docker-py
      pip:
        name: docker-py

